# Add a new category
POST http://localhost:3001/api/admin/categories
Content-Type: application/json
Admin-Secret-Key: admin

{
  "name": "example"
}

###

# Edit the category (Replace CATEGORY_ID with the actual ID of the created category)
PUT http://localhost:3001/api/admin/categories/65ad860598faf8fcc32dbdcc
Content-Type: application/json
Admin-Secret-Key: admin

{
  "name": "example2"
}

###

# Delete the category (Replace CATEGORY_ID with the actual ID of the created category)
DELETE http://localhost:3001/api/admin/categories/65ad860598faf8fcc32dbdcc
Admin-Secret-Key: admin