# Add a new product
POST http://localhost:3001/api/admin/products
Content-Type: application/json
Admin-Secret-Key: admin

{
  "name": "Example Product",
  "price": 9.99,
  "category": "Wegetariańskie",
  "ingredients": ["Ingredient1", "Ingredient2"],
  "image": "http://example.com/image.jpg"
}

###

# Edit the product (Replace PRODUCT_ID with the actual ID of the created product)
PUT http://localhost:3001/api/admin/products/65ad867798faf8fcc32dbdd0
Content-Type: application/json
Admin-Secret-Key: admin

{
  "name": "Updated Example Product",
  "price": 11.99,
  "category": "Wegetariańskie",
  "ingredients": ["UpdatedIngredient1", "UpdatedIngredient2"],
  "image": "http://example.com/newimage.jpg"
}

###

# Delete the product (Replace PRODUCT_ID with the actual ID of the created product)
DELETE http://localhost:3001/api/admin/products/65ad867798faf8fcc32dbdd0
Admin-Secret-Key: admin
